export type Submission = {
  id: number;
  created_at: string;
  fecha: string | null;
  persona_tipo?: 'individual' | 'juridica' | string;
  origen_compra?: 'guatemala' | 'extranjero' | string | null;
  unidad_clave?: string | null;
  gestion_nombre?: string | null;
  registro_codigo?: string | null;
  nombre_propietario: string;
  representante_legal?: string;
  documento_propietario?: string;
  direccion?: string;
  telefono?: string;
  correo: string;
  nit?: string;
  nombre_orden_pago?: string;
  autorizado_nombre?: string;
  autorizado_documento?: string;
  autorizado_telefono?: string;
  ubicacion_inspeccion?: string;
  matricula_tg?: string;
  matricula_tg_nueva?: string;
  uso?: string;
  fabricante?: string;
  numero_serie?: string;
  modelo?: string;
  anio_fabricacion?: string;
  colores?: string;
  tipo_internacion: boolean;
  tipo_reservacion: boolean;
  tipo_inscripcion: boolean;
  tipo_certificado_prov: boolean;
  tipo_reposicion: boolean;
  tipo_cambio_prop: boolean;
  tipo_cambio_datos: boolean;
  tipo_certificacion: boolean;
  especificaciones?: string;
  comentarios_revision?: string;
  detalle_formulario?: Record<string, unknown> | null;
  dpi_filename?: string | null;
  dpi_mime?: string | null;
  has_dpi?: boolean | null;
  financial_declaraguate_2_filename?: string | null;
  financial_declaraguate_2_mime?: string | null;
  has_financial_declaraguate_2?: boolean | null;
  financial_declaraguate_3_filename?: string | null;
  financial_declaraguate_3_mime?: string | null;
  has_financial_declaraguate_3?: boolean | null;
  financial_declaraguate_4_filename?: string | null;
  financial_declaraguate_4_mime?: string | null;
  has_financial_declaraguate_4?: boolean | null;
  financial_declaraguate_5_filename?: string | null;
  financial_declaraguate_5_mime?: string | null;
  has_financial_declaraguate_5?: boolean | null;
  acta_filename?: string | null;
  acta_mime?: string | null;
  has_acta?: boolean | null;
  carta_representacion_filename?: string | null;
  carta_representacion_mime?: string | null;
  has_carta_representacion?: boolean | null;
  registro_mercantil_filename?: string | null;
  registro_mercantil_mime?: string | null;
  has_registro_mercantil?: boolean | null;
  rpa_acta_nombramiento_filename?: string | null;
  rpa_acta_nombramiento_mime?: string | null;
  has_rpa_acta_nombramiento?: boolean | null;
  rpa_registro_representante_filename?: string | null;
  rpa_registro_representante_mime?: string | null;
  has_rpa_registro_representante?: boolean | null;
  rpa_registro_entidad_filename?: string | null;
  rpa_registro_entidad_mime?: string | null;
  has_rpa_registro_entidad?: boolean | null;
  rpa_documento_estado_filename?: string | null;
  rpa_documento_estado_mime?: string | null;
  has_rpa_documento_estado?: boolean | null;
  analyst_pdf_filename?: string | null;
  analyst_pdf_mime?: string | null;
  analyst_pdf_uploaded_at?: string | null;
  analyst_pdf_uploaded_by_user_id?: number | null;
  has_analyst_pdf?: boolean | null;
  signed_pdf_filename?: string | null;
  signed_pdf_mime?: string | null;
  signed_pdf_uploaded_at?: string | null;
  has_signed_pdf?: boolean | null;
  feedback_rating?: number | null;
  feedback_comment?: string | null;
  feedback_created_at?: string | null;
  receptor_opened_at?: string | null;
  approved_at?: string | null;
  approved_by_user_id?: number | null;
  delivered_at?: string | null;
  delivered_by_user_id?: number | null;
  returned_at?: string | null;
  returned_reason?: string | null;
  returned_by_user_id?: number | null;
  returned_to_analista_at?: string | null;
  returned_to_analista_reason?: string | null;
  returned_to_analista_by_user_id?: number | null;
  assigned_analista_id?: number | null;
  assigned_analista_email?: string | null;
  assigned_analista_name?: string | null;
  assigned_emisor_id?: number | null;
  assigned_emisor_email?: string | null;
  assigned_emisor_name?: string | null;
  assigned_aprobador_id?: number | null;
  assigned_aprobador_email?: string | null;
  assigned_aprobador_name?: string | null;
  sent_to_emisor_at?: string | null;
  sent_to_aprobador_at?: string | null;
  process_code?: string;
  process_label?: string;
  process_step?: number;
  process_percent?: number;
};
