export type Submission = {
  id: number;
  created_at: string;
  fecha: string | null;
  persona_tipo?: 'individual' | 'juridica' | string;
  unidad_clave?: string | null;
  gestion_nombre?: string | null;
  registro_codigo?: string | null;
  nombre_propietario: string;
  representante_legal?: string;
  documento_propietario?: string;
  direccion?: string;
  telefono?: string;
  correo: string;
  nit?: string;
  nombre_orden_pago?: string;
  autorizado_nombre?: string;
  autorizado_documento?: string;
  autorizado_telefono?: string;
  ubicacion_inspeccion?: string;
  matricula_tg?: string;
  matricula_tg_nueva?: string;
  uso?: string;
  fabricante?: string;
  numero_serie?: string;
  modelo?: string;
  anio_fabricacion?: string;
  colores?: string;
  tipo_internacion: boolean;
  tipo_reservacion: boolean;
  tipo_inscripcion: boolean;
  tipo_certificado_prov: boolean;
  tipo_reposicion: boolean;
  tipo_cambio_prop: boolean;
  tipo_cambio_datos: boolean;
  tipo_certificacion: boolean;
  especificaciones?: string;
  comentarios_revision?: string;
  dpi_filename?: string | null;
  dpi_mime?: string | null;
  has_dpi?: boolean | null;
  acta_filename?: string | null;
  acta_mime?: string | null;
  has_acta?: boolean | null;
  registro_mercantil_filename?: string | null;
  registro_mercantil_mime?: string | null;
  has_registro_mercantil?: boolean | null;
  analyst_pdf_filename?: string | null;
  analyst_pdf_mime?: string | null;
  analyst_pdf_uploaded_at?: string | null;
  analyst_pdf_uploaded_by_user_id?: number | null;
  has_analyst_pdf?: boolean | null;
  feedback_rating?: number | null;
  feedback_comment?: string | null;
  feedback_created_at?: string | null;
  receptor_opened_at?: string | null;
  approved_at?: string | null;
  approved_by_user_id?: number | null;
  returned_at?: string | null;
  returned_reason?: string | null;
  returned_by_user_id?: number | null;
  returned_to_analista_at?: string | null;
  returned_to_analista_reason?: string | null;
  returned_to_analista_by_user_id?: number | null;
  assigned_analista_id?: number | null;
  assigned_analista_email?: string | null;
  assigned_analista_name?: string | null;
  assigned_aprobador_id?: number | null;
  assigned_aprobador_email?: string | null;
  assigned_aprobador_name?: string | null;
  sent_to_aprobador_at?: string | null;
  process_code?: string;
  process_label?: string;
  process_step?: number;
  process_percent?: number;
};
